export const AUTHENTICATE_USER = {
  REQUEST: "AUTHENTICATE_USER_REQUEST",
  SUCCESS: "AUTHENTICATE_USER_SUCCESS",
  FAILURE: "AUTHENTICATE_USER_FAILURE",
};

export const PROFILE_UPDATE = {
  REQUEST: "PROFILE_UPDATE_REQUEST",
  SUCCESS: "PROFILE_UPDATE_SUCCESS",
  FAILURE: "PROFILE_UPDATE_FAILURE",
};

export const GET_USER = {
  REQUEST: "GET_USER_REQUEST",
  SUCCESS: "GET_USER_SUCCESS",
  FAILURE: "GET_USER_FAILURE",
};

export const LOGIN_USER = {
  REQUEST: "LOGIN_USER_REQUEST",
  SUCCESS: "LOGIN_USER_SUCCESS",
  FAILURE: "LOGIN_USER_FAILURE",
};

export const GET_PHONE_NUMBERS = {
  REQUEST: "GET_PHONE_NUMBERS_REQUEST",
  SUCCESS: "GET_PHONE_NUMBERS_SUCCESS",
  FAILURE: "GET_PHONE_NUMBERS_FAILURE",
};

export const SET_PHONE_NUMBERS = {
  REQUEST: "SET_PHONE_NUMBERS_REQUEST",
  SUCCESS: "SET_PHONE_NUMBERS_SUCCESS",
  FAILURE: "SET_PHONE_NUMBERS_FAILURE",
};

export const GET_SOCIALS = {
  REQUEST: "GET_SOCIALS_REQUEST",
  SUCCESS: "GET_SOCIALS_SUCCESS",
  FAILURE: "GET_SOCIALS_FAILURE",
};

export const SET_SOCIALS = {
  REQUEST: "SET_SOCIALS_REQUEST",
  SUCCESS: "SET_SOCIALS_SUCCESS",
  FAILURE: "SET_SOCIALS_FAILURE",
};

export const GET_ACTIVE_DEVICES = {
  REQUEST: "GET_ACTIVE_DEVICES_REQUEST",
  SUCCESS: "GET_ACTIVE_DEVICES_SUCCESS",
  FAILURE: "GET_ACTIVE_DEVICES_FAILURE",
};

export const GET_AUTH_HISTORY = {
  REQUEST: "GET_AUTH_HISTORY_REQUEST",
  SUCCESS: "GET_AUTH_HISTORY_SUCCESS",
  FAILURE: "GET_AUTH_HISTORY_FAILURE",
};

export const DEACTIVATE_TOKEN = {
  REQUEST: "DEACTIVATE_TOKEN_REQUEST",
  SUCCESS: "DEACTIVATE_TOKEN_SUCCESS",
};

export const DEACTIVATE_ALL_TOKENS = {
  REQUEST: "DEACTIVATE_ALL_TOKENS_REQUEST",
  SUCCESS: "DEACTIVATE_ALL_TOKENS_SUCCESS",
  FAILURE: "DEACTIVATE_ALL_TOKENS_FAILURE",
};

export const CHANGE_TOKEN_EXPIRED_TIME = {
  REQUEST: "CHANGE_TOKEN_EXPIRED_TIME_REQUEST",
  SUCCESS: "CHANGE_TOKEN_EXPIRED_TIME_SUCCESS",
  FAILURE: "CHANGE_TOKEN_EXPIRED_TIME_FAILURE",
};

export const LOGOUT_USER = "LOGOUT_USER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USER_LOCATION = "SET_USER_LOCATION";

export const CREATE_ORG = {
  REQUEST: "CREATE_ORG_REQUEST",
  SUCCESS: "CREATE_ORG_SUCCESS",
  FAILURE: "CREATE_ORG_FAILURE",
};

export const GET_ORG = {
  REQUEST: "GET_ORG_REQUEST",
  SUCCESS: "GET_ORG_SUCCESS",
  FAILURE: "GET_ORG_FAILURE",
};

export const GET_ORG_HOTLINKS = {
  REQUEST: "GET_ORG_HOTLINKS_REQUEST",
  SUCCESS: "GET_ORG_HOTLINKS_SUCCESS",
  FAILURE: "GET_ORG_HOTLINKS_FAILURE",
};

export const GET_ORG_HOTLINK_DETAILS = {
  REQUEST: "GET_ORG_HOTLINK_DETAILS_REQUEST",
  SUCCESS: "GET_ORG_HOTLINK_DETAILS_SUCCESS",
  FAILURE: "GET_ORG_HOTLINK_DETAILS_FAILURE",
};

export const GET_ORG_LIST = {
  REQUEST: "GET_ORG_LIST_REQUEST",
  SUCCESS: "GET_ORG_LIST_SUCCESS",
  FAILURE: "GET_ORG_LIST_FAILURE",
};

export const GET_ORG_TYPES = {
  REQUEST: "GET_ORG_TYPES_REQUEST",
  SUCCESS: "GET_ORG_TYPES_SUCCESS",
  FAILURE: "GET_ORG_TYPES_FAILURE",
};

export const GET_ORG_SUB_TYPES = {
  REQUEST: "GET_ORG_SUB_TYPES_REQUEST",
  SUCCESS: "GET_ORG_SUB_TYPES_SUCCESS",
  FAILURE: "GET_ORG_SUB_TYPES_FAILURE",
};

export const GET_ORG_PROMOTION = {
  REQUEST: "GET_ORG_PROMOTION_REQUEST",
  SUCCESS: "GET_ORG_PROMOTION_SUCCESS",
  FAILURE: "GET_ORG_PROMOTION_FAILURE",
};

export const GET_ORG_COLLECTION_ITEMS = {
  REQUEST: "GET_ORG_COLLECTION_ITEMS_REQUEST",
  SUCCESS: "GET_ORG_COLLECTION_ITEMS_SUCCESS",
  FAILURE: "GET_ORG_COLLECTION_ITEMS_FAILURE",
};

export const GET_ORG_COLLECTION_SUBCATEGORIES = {
  REQUEST: "GET_ORG_COLLECTION_SUBCATEGORIES_REQUEST",
  SUCCESS: "GET_ORG_COLLECTION_SUBCATEGORIES_SUCCESS",
  FAILURE: "GET_ORG_COLLECTION_SUBCATEGORIES_FAILURE",
};

export const GET_SELECTED_HOTLINK_COLLECTION_ITEMS = {
  REQUEST: "GET_SELECTED_HOTLINK_COLLECTION_ITEMS_REQUEST",
  SUCCESS: "GET_SELECTED_HOTLINK_COLLECTION_ITEMS_SUCCESS",
  FAILURE: "GET_SELECTED_HOTLINK_COLLECTION_ITEMS_FAILURE",
  CLEAR: "GET_SELECTED_HOTLINK_COLLECTION_ITEMS_CLEAR",
};

export const GET_CURRENCY = {
  REQUEST: "GET_CURRENCY_REQUEST",
  SUCCESS: "GET_CURRENCY_SUCCESS",
  FAILURE: "GET_CURRENCY_FAILURE",
};

export const GET_CITIES_AND_COUNTRIES = {
  REQUEST: "GET_CITIES_AND_COUNTRIES_REQUEST",
  SUCCESS: "GET_CITIES_AND_COUNTRIES_SUCCESS",
  FAILURE: "GET_CITIES_AND_COUNTRIES_FAILURE",
};

export const GET_SERVICE_ORGANIZATIONS = {
  REQUEST: "GET_SERVICE_ORGANIZATIONS_REQUEST",
  SUCCESS: "GET_SERVICE_ORGANIZATIONS_SUCCESS",
  FAILURE: "GET_SERVICE_ORGANIZATIONS_FAILURE",
};

export const GET_CARD_BACKGROUNDS = {
  REQUEST: "GET_CARD_BACKGROUNDS_REQUEST",
  SUCCESS: "GET_CARD_BACKGROUNDS_SUCCESS",
  FAILURE: "GET_CARD_BACKGROUNDS_FAILURE",
};

export const GET_TRANSLATION_SHOP_ITEM = {
  REQUEST: "GET_TRANSLATION_SHOP_ITEM_REQUEST",
  SUCCESS: "GET_TRANSLATION_SHOP_ITEM_SUCCESS",
  FAILURE: "GET_TRANSLATION_SHOP_ITEM_FAILURE",
};

export const GET_LANGUAGE_TRANSLATE_LIST = {
  REQUEST: "GET_LANGUAGE_TRANSLATE_LIST_REQUEST",
  SUCCESS: "GET_LANGUAGE_TRANSLATE_LIST_SUCCESS",
  FAILURE: "GET_LANGUAGE_TRANSLATE_LIST_FAILURE",
};

export const GET_CURRENCY_CONVERSION = {
  REQUEST: "GET_CURRENCY_CONVERSION_REQUEST",
  SUCCESS: "GET_CURRENCY_CONVERSION_SUCCESS",
  FAILURE: "GET_CURRENCY_CONVERSION_FAILURE",
};

export const GET_SERVICE_CATEGORIES = {
  REQUEST: "GET_SERVICE_CATEGORIES_REQUEST",
  SUCCESS: "GET_SERVICE_CATEGORIES_SUCCESS",
  FAILURE: "GET_SERVICE_CATEGORIES_FAILURE",
};

export const ACCEPT_OR_CANCEL_FOLLOWER = {
  REQUEST: "ACCEPT_OR_CANCEL_FOLLOWER_REQUEST",
  SUCCESS: "ACCEPT_OR_CANCEL_FOLLOWER_SUCCESS",
  FAILURE: "ACCEPT_OR_CANCEL_FOLLOWER_FAILURE",
};

export const ACCEPT_ALL_FOLLOWERS = {
  REQUEST: "ACCEPT_ALL_FOLLOWERS_REQUEST",
  SUCCESS: "ACCEPT_ALL_FOLLOWERS_SUCCESS",
  FAILURE: "ACCEPT_ALL_FOLLOWERS_FAILURE",
};

export const GET_COMMENTED_ITEMS = {
  REQUEST: "GET_COMMENTED_ITEMS_REQUEST",
  SUCCESS: "GET_COMMENTED_ITEMS_SUCCESS",
  FAILURE: "GET_COMMENTED_ITEMS_FAILURE",
};

export const GET_USER_EMAIL_BY_PHONE_NUMBER = {
  REQUEST: "GET_USER_EMAIL_BY_PHONE_NUMBER_REQUEST",
  SUCCESS: "GET_USER_EMAIL_BY_PHONE_NUMBER_SUCCESS",
  FAILURE: "GET_USER_EMAIL_BY_PHONE_NUMBER_FAILURE",
};

export const SET_ORGANIZATION_DETAIL = "SET_ORGANIZATION_DETAIL";
export const SUBSCRIBE_ORGANIZATION = "SUBSCRIBE_ORGANIZATION";
export const SET_AUTH_CHANGE_CODE = "SET_AUTH_CHANGE_CODE";
export const SET_PRE_ORGANIZATION = "SET_PRE_ORGANIZATION";
export const SET_USER_GEO = "SET_USER_GEO";
export const SET_REGION = "SET_REGION";
export const SET_LOCALE = "SET_LOCALE";
export const SET_TOOLTIP_PLAYER = "SET_TOOLTIP_PLAYER";
export const SET_PLAYING_VIDEO_ID = "SET_PLAYING_VIDEO_ID";
export const SET_VIEWS = "SET_VIEWS";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_GLOBAL_MENU = "SET_GLOBAL_MENU";
export const SET_PRINT_PAPER_WIDTH = "SET_PRINT_PAPER_WIDTH";
export const SET_SERVICES_LIST = "SET_SERVICES_LIST";
export const SET_SHOW_QR = "SET_SHOW_QR";
export const CLEAR_TRANSLATE_ITEMS = "CLEAR_TRANSLATE_ITEMS";
export const CLEAR_CONVERTED_ITEMS = "CLEAR_CONVERTED_ITEM";
export const CLEAR_SERVICE_DATA = "CLEAR_SERVICE_DATA";
export const SET_TYPE_RESEND_CODE = "SET_TYPE_RESEND_CODE";

export const SET_ORGANIZATIONS_MAP_REGION = "SET_ORGANIZATIONS_MAP_REGION";
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";


export const SET_ORG_DETAIL = "SET_ORG_DETAIL";
export const CLEAR_ORG_DETAIL = "CLEAR_ORG_DETAIL";