export const GET_ATTENDANCE_STATUS = {
  REQUEST: 'GET_ATTENDANCE_STATUS_REQUEST',
  SUCCESS: 'GET_ATTENDANCE_STATUS_SUCCESS',
  FAILURE: 'GET_ATTENDANCE_STATUS_FAILURE',
}

export const GET_RECEIPTS_CALENDAR = {
  REQUEST: 'GET_RECEIPTS_CALENDAR_REQUEST',
  SUCCESS: 'GET_RECEIPTS_CALENDAR_SUCCESS',
  FAILURE: 'GET_RECEIPTS_CALENDAR_FAILURE',
}