export const GET_BANNER_ORGANIZATIONS = {
  REQUEST: 'GET_BANNER_ORGANIZATIONS_REQUEST',
  SUCCESS: 'GET_BANNER_ORGANIZATIONS_SUCCESS',
  FAILURE: 'GET_BANNER_ORGANIZATIONS_FAILURE',
}

export const GET_BANNERS_LIST = {
  REQUEST: 'GET_BANNERS_LIST_REQUEST',
  SUCCESS: 'GET_BANNERS_LIST_SUCCESS',
  FAILURE: 'GET_BANNERS_LIST_FAILURE',
}

export const GET_BANNER_DETAIL = {
  REQUEST: 'GET_BANNER_DETAIL_REQUEST',
  SUCCESS: 'GET_BANNER_DETAIL_SUCCESS',
  FAILURE: 'GET_BANNER_DETAIL_FAILURE',
}