export const GET_CARTS_LIST = {
  REQUEST: "GET_CARTS_LIST_REQUEST",
  SUCCESS: "GET_CARTS_LIST_SUCCESS",
  FAILURE: "GET_CARTS_LIST_FAILURE",
};

export const PUT_CART_DETAIL = {
  REQUEST: "PUT_CART_DETAIL_REQUEST",
  SUCCESS: "PUT_CART_DETAIL_SUCCESS",
  FAILURE: "PUT_CART_DETAIL_FAILURE",
};

export const GET_CART_DETAIL = {
  REQUEST: "GET_CART_DETAIL_REQUEST",
  SUCCESS: "GET_CART_DETAIL_SUCCESS",
  FAILURE: "GET_CART_DETAIL_FAILURE",
};

export const CLEAR_CARTS_LIST = "CLEAR_CARTS_LIST";

export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";

export const SET_CART_DETAIL = "SET_CART_DETAIL";
