export const SET_DELIVERY_AVAILABLE_ORDERS_COUNT = 'SET_DELIVERY_AVAILABLE_ORDERS_COUNT';

export const GET_AVAILABLE_ORDERS_FOR_DELIVERY = {
  REQUEST: 'GET_AVAILABLE_ORDERS_FOR_DELIVERY_REQUEST',
  SUCCESS: 'GET_AVAILABLE_ORDERS_FOR_DELIVERY_SUCCESS',
  FAILURE: 'GET_AVAILABLE_ORDERS_FOR_DELIVERY_FAILURE',
}

export const GET_HISTORY_ORDERS_FOR_DELIVERY = {
  REQUEST: 'GET_HISTORY_ORDERS_FOR_DELIVERY_REQUEST',
  SUCCESS: 'GET_HISTORY_ORDERS_FOR_DELIVERY_SUCCESS',
  FAILURE: 'GET_HISTORY_ORDERS_FOR_DELIVERY_FAILURE',
}