export const GET_EMPLOYEES = {
  REQUEST: 'GET_EMPLOYEES_REQUEST',
  SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  FAILURE: 'GET_EMPLOYEES_FAILURE',
}

export const GET_ROLES = {
  REQUEST: 'GET_ROLES_REQUEST',
  SUCCESS: 'GET_ROLES_SUCCESS',
  FAILURE: 'GET_ROLES_FAILURE',
}

export const GET_ROLE_DETAIL = {
  REQUEST: 'GET_ROLE_DETAIL_REQUEST',
  SUCCESS: 'GET_ROLE_DETAIL_SUCCESS',
  FAILURE: 'GET_ROLE_DETAIL_FAILURE',
}

export const GET_EMPLOYEE_DETAIL = {
  REQUEST: 'GET_EMPLOYEE_DETAIL_REQUEST',
  SUCCESS: 'GET_EMPLOYEE_DETAIL_SUCCESS',
  FAILURE: 'GET_EMPLOYEE_DETAIL_FAILURE',
}

export const GET_EMPLOYEE_INFO = 'GET_EMPLOYEE_INFO';