export const GET_HOME_ORGANIZATIONS = {
  REQUEST: 'GET_HOME_ORGANIZATIONS_REQUEST',
  SUCCESS: 'GET_HOME_ORGANIZATIONS_SUCCESS',
  FAILURE: 'GET_HOME_ORGANIZATIONS_FAILURE',
}

export const GET_HOME_PARTNERS = {
  REQUEST: 'GET_HOME_PARTNERS_REQUEST',
  SUCCESS: 'GET_HOME_PARTNERS_SUCCESS',
  FAILURE: 'GET_HOME_PARTNERS_FAILURE',
}

export const GET_PARTNERS_LIST = {
  REQUEST: 'GET_PARTNERS_LIST_REQUEST',
  SUCCESS: 'GET_PARTNERS_LIST_SUCCESS',
  FAILURE: 'GET_PARTNERS_LIST_FAILURE',
}

export const GET_ORGS_BY_CATEGORIES = {
  REQUEST: 'GET_ORGS_BY_CATEGORIES_REQUEST',
  SUCCESS: 'GET_ORGS_BY_CATEGORIES_SUCCESS',
  FAILURE: 'GET_ORGS_BY_CATEGORIES_FAILURE',
}

export const GET_LOCAL_BANNERS = {
  REQUEST: 'GET_LOCAL_BANNERS_REQUEST',
  SUCCESS: 'GET_LOCAL_BANNERS_SUCCESS',
  FAILURE: 'GET_LOCAL_BANNERS_FAILURE',
}

export const GET_SEARCH_RESULT = {
  REQUEST: 'GET_SEARCH_RESULT_REQUEST',
  SUCCESS: 'GET_SEARCH_RESULT_SUCCESS',
  FAILURE: 'GET_SEARCH_RESULT_FAILURE',
}

export const GET_SEARCH_SUGGEST_RESULT = {
  REQUEST: 'GET_SEARCH_SUGGEST_RESULT_REQUEST',
  SUCCESS: 'GET_SEARCH_SUGGEST_RESULT_SUCCESS',
  FAILURE: 'GET_SEARCH_SUGGEST_RESULT_FAILURE',
}

export const CLEAR_SEARCH_SUGGEST_RESULT = 'CLEAR_SEARCH_SUGGEST_RESULT';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';