export const GET_ORG_MESSAGES = {
  REQUEST: 'GET_ORG_MESSAGES_REQUEST',
  SUCCESS: 'GET_ORG_MESSAGES_SUCCESS',
  FAILURE: 'GET_ORG_MESSAGES_FAILURE',
}

export const CREATE_ORG_MESSAGE = {
  REQUEST: 'CREATE_ORG_MESSAGE_REQUEST',
  SUCCESS: 'CREATE_ORG_MESSAGE_SUCCESS',
  FAILURE: 'CREATE_ORG_MESSAGE_FAILURE',
}

export const GET_SUBSCRIPTION_MESSAGES = {
  REQUEST: 'GET_SUBSCRIPTION_MESSAGES_REQUEST',
  SUCCESS: 'GET_SUBSCRIPTION_MESSAGES_SUCCESS',
  FAILURE: 'GET_SUBSCRIPTION_MESSAGES_FAILURE',
}
