export const GET_NOTIFICATIONS = {
  REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  FAILURE: 'GET_NOTIFICATIONS_FAILURE',
}

export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';