export const GET_ORG_FOLLOWERS = {
  REQUEST: "GET_ORG_FOLLOWERS_REQUEST",
  SUCCESS: "GET_ORG_FOLLOWERS_SUCCESS",
  FAILURE: "GET_ORG_FOLLOWERS_FAILURE",
};

export const GET_ORG_PROMOTIONS = {
  REQUEST: "GET_ORG_PROMOTIONS_REQUEST",
  SUCCESS: "GET_ORG_PROMOTIONS_SUCCESS",
  FAILURE: "GET_ORG_PROMOTIONS_FAILURE",
};

export const GET_ORG_SHADOW_BAN_STATUS = {
  REQUEST: "GET_ORG_SHADOW_BAN_STATUS_REQUEST",
  SUCCESS: "GET_ORG_SHADOW_BAN_STATUS_SUCCESS",
  FAILURE: "GET_ORG_SHADOW_BAN_STATUS_FAILURE",
};

export const SEND_REMOVE_ORG_FROM_SHADOW_BAN = {
  REQUEST: "SEND_REMOVE_SHADOW_BAN_REQUEST",
  SUCCESS: "SEND_REMOVE_SHADOW_BAN_SUCCESS",
  FAILURE: "SEND_REMOVE_SHADOW_BAN_FAILURE",
};

export const SEND_VERIFICATION_ORGANIZATION = {
  REQUEST: "SEND_VERIFICATION_ORGANIZATION_REQUEST",
  SUCCESS: "SEND_VERIFICATION_ORGANIZATION_SUCCESS",
  FAILURE: "SEND_VERIFICATION_ORGANIZATION_FAILURE",
};

export const GET_ORGANIZATION_POSTS = {
  REQUEST: "GET_ORGANIZATION_POSTS_REQUEST",
  SUCCESS: "GET_ORGANIZATION_POSTS_SUCCESS",
  FAILURE: "GET_ORGANIZATION_POSTS_FAILURE",
};

export const SET_ORGANIZATION_POSTS_STATE = "SET_ORGANIZATION_POSTS_STATE";

export const GET_ORGANIZATION_SUBCATEGORIES = {
  REQUEST: "GET_ORGANIZATION_SUBCATEGORIES_REQUEST",
  SUCCESS: "GET_ORGANIZATION_SUBCATEGORIES_SUCCESS",
  FAILURE: "GET_ORGANIZATION_SUBCATEGORIES_FAILURE",
};

export const GET_ORGANIZATION_SUBCATEGORIES_BY_POST = {
  REQUEST: "GET_ORGANIZATION_SUBCATEGORIES_BY_POST_REQUEST",
  SUCCESS: "GET_ORGANIZATION_SUBCATEGORIES_BY_POST_SUCCESS",
  FAILURE: "GET_ORGANIZATION_SUBCATEGORIES_BY_POST_FAILURE",
};

export const GET_ORGANIZATION_CLIENT_DETAILS = {
  REQUEST: "GET_ORGANIZATION_CLIENT_DETAIL_REQUEST",
  SUCCESS: "GET_ORGANIZATION_CLIENT_DETAIL_SUCCESS",
  FAILURE: "GET_ORGANIZATION_CLIENT_DETAIL_FAILURE",
};

export const SET_CLOSE_ORG_SHADOW_BAN = "SET_CLOSE_ORG_SHADOW_BAN";

export const SET_SELECTED_HOTLINK_COLLECTION_SUBCATEGORIES =
  "SET_SELECTED_HOTLINK_COLLECTION_SUBCATEGORIES";
export const SET_ORG_CLIENT = "SET_ORG_CLIENT";
export const SET_ORG_TITLE = "SET_ORG_TITLE";
export const SET_USER_LIMITS = "SET_USER_LIMITS";

export const SET_MY_PURCHASES_ORGANIZATIONS = "SET_MY_PURCHASES_ORGANIZATIONS";
export const SET_MY_AFFILIATED_ORGANIZATION = "SET_MY_AFFILIATED_ORGANIZATION";

export const SET_MY_RENT_PURCHASES_ORGANIZATIONS =
  "SET_MY_RENT_PURCHASES_ORGANIZATIONS";
export const SET_MY_AFFILIATED_RENT_ORGANIZATIONS =
  "SET_MY_AFFILIATED_RENT_ORGANIZATIONS";

export const SET_ORG_CLIENT_DETAILS = "SET_ORG_CLIENT_DETAILS";
export const CLEAR_ORG_CLIENT_DETAILS = "CLEAR_ORG_CLIENT_DETAILS";
export const SET_ORGANIZATION_CATEGORY_CACHE =
  "SET_ORGANIZATION_CATEGORY_CACHE";
export const CLEAR_ORGANIZATION_CATEGORY_CACHE =
  "CLEAR_ORGANIZATION_CATEGORY_CACHE";

export const SET_ORGANIZATION_CREATION_INITIAL_DATA =
  "SET_ORGANIZATION_CREATION_INITIAL_DATA";

export const ADD_ORGANIZATION_POST = "ADD_ORGANIZATION_POST";

export const CLEAR_ORGANIZATION_POSTS = "CLEAR_ORGANIZATION_POSTS";

export const UPDATE_POST_IN_CACHE = "UPDATE_POST_IN_CACHE_ORG";

// export const ADD_ORGANIZATION_POST = "ADD_ORGANIZATION_POST";
