export const GET_ORG_PARTNERS = {
  REQUEST: 'GET_ORG_PARTNERS_REQUEST',
  SUCCESS: 'GET_ORG_PARTNERS_SUCCESS',
  FAILURE: 'GET_ORG_PARTNERS_FAILURE',
}

export const GET_ORG_PARTNERSHIPS = {
  REQUEST: 'GET_ORG_PARTNERSHIPS_REQUEST',
  SUCCESS: 'GET_ORG_PARTNERSHIPS_SUCCESS',
  FAILURE: 'GET_ORG_PARTNERSHIPS_FAILURE',
}

export const GET_PARTNERSHIP_DETAIL = {
  REQUEST: 'GET_PARTNERSHIP_DETAIL_REQUEST',
  SUCCESS: 'GET_PARTNERSHIP_DETAIL_SUCCESS',
  FAILURE: 'GET_PARTNERSHIP_DETAIL_FAILURE',
}

export const GET_PARTNER_POSTS = {
  REQUEST: 'GET_PARTNER_POSTS_REQUEST',
  SUCCESS: 'GET_PARTNER_POSTS_SUCCESS',
  FAILURE: 'GET_PARTNER_POSTS_FAILURE',
}

export const GET_PARTNER_CATEGORIES = {
  REQUEST: 'GET_PARTNER_CATEGORIES_REQUEST',
  SUCCESS: 'GET_PARTNER_CATEGORIES_SUCCESS',
  FAILURE: 'GET_PARTNER_CATEGORIES_FAILURE',
}

export const GET_PARTNER_SUBCATEGORIES = {
  REQUEST: 'GET_PARTNER_SUBCATEGORIES_REQUEST',
  SUCCESS: 'GET_PARTNER_SUBCATEGORIES_SUCCESS',
  FAILURE: 'GET_PARTNER_SUBCATEGORIES_FAILURE',
}

export const GET_SEARCH_PARTNER_RESULT = {
  REQUEST: 'GET_SEARCH_PARTNER_RESULT_REQUEST',
  SUCCESS: 'GET_SEARCH_PARTNER_RESULT_SUCCESS',
  FAILURE: 'GET_SEARCH_PARTNER_RESULT_FAILURE',
}

export const CHANGE_PARTNER_POSTS_VIEW = 'CHANGE_PARTNER_POSTS_VIEW'

export const MODIFY_PARTNER_POSTS = 'MODIFY_PARTNER_POSTS'