export const GET_POSTS = {
  REQUEST: "GET_POSTS_REQUEST",
  SUCCESS: "GET_POSTS_SUCCESS",
  FAILURE: "GET_POSTS_FAILURE",
};

export const GET_POSTS_NON_EMPTY_CATEGORIES_SUCCESS =
  "GET_POSTS_NON_EMPTY_CATEGORIES_SUCCESS";
export const SET_POSTS_MODIFIER = "SET_POSTS_MODIFIER";

export const GET_CATEGORY_DETAIL = {
  REQUEST: "GET_CATEGORY_DETAIL_REQUEST",
  SUCCESS: "GET_CATEGORY_DETAIL_SUCCESS",
  FAILURE: "GET_CATEGORY_DETAIL_FAILURE",
};

export const SET_SELECTED_SUBCATEGORY = "SET_SELECTED_SUBCATEGORY";
export const SET_VIEWED_POST = "SET_VIEWED_POST";
export const UPDATE_POST_IN_CACHE = "UPDATE_POST_IN_CACHE";

export const GET_POST_DETAIL = {
  REQUEST: "GET_POST_DETAIL_REQUEST",
  SUCCESS: "GET_POST_DETAIL_SUCCESS",
  FAILURE: "GET_POST_DETAIL_FAILURE",
};

export const GET_ORG_POSTS_LIST = {
  REQUEST: "GET_ORG_POSTS_LIST_REQUEST",
  SUCCESS: "GET_ORG_POSTS_LIST_SUCCESS",
  FAILURE: "GET_ORG_POSTS_LIST_FAILURE",
};

export const GET_POST_CATEGORIES = {
  REQUEST: "GET_POST_CATEGORIES_REQUEST",
  SUCCESS: "GET_POST_CATEGORIES_SUCCESS",
  FAILURE: "GET_POST_CATEGORIES_FAILURE",
};

export const GET_POST_SUBCATEGORIES = {
  REQUEST: "GET_POST_SUBCATEGORIES_REQUEST",
  SUCCESS: "GET_POST_SUBCATEGORIES_SUCCESS",
  FAILURE: "GET_POST_SUBCATEGORIES_FAILURE",
};

export const GET_TRANSLATION_POST = {
  REQUEST: "GET_TRANSLATION_POST_REQUEST",
  SUCCESS: "GET_TRANSLATION_POST_SUCCESS",
  FAILURE: "GET_TRANSLATION_POST_FAILURE",
};

export const GET_POST_COMMENTS = {
  REQUEST: "GET_POST_COMMENTS_REQUEST",
  SUCCESS: "GET_POST_COMMENTS_SUCCESS",
  FAILURE: "GET_POST_COMMENTS_FAILURE",
};

export const CREATE_POST_COMMENT = {
  REQUEST: "CREATE_POST_COMMENT_REQUEST",
  SUCCESS: "CREATE_POST_COMMENT_SUCCESS",
  FAILURE: "CREATE_POST_COMMENT_FAILURE",
};

export const DELETE_COMMENT = {
  REQUEST: "DELETE_COMMENT_REQUEST",
  SUCCESS: "DELETE_COMMENT_SUCCESS",
  FAILURE: "DELETE_COMMENT_FAILURE",
};

export const COMMENT_LIKE = {
  REQUEST: "COMMENT_LIKE_REQUEST",
  SUCCESS: "COMMENT_LIKE_SUCCESS",
  FAILURE: "COMMENT_LIKE_FAILURE",
};

export const SET_COMMENTS = "SET_COMMENTS";

export const HIDE_COMMENT = "HIDE_COMMENT";

export const UPDATE_COMMENT = "UPDATE_COMMENT";

export const BLOCK_COMMENTS_USER = "BLOCK_COMMENT";

export const UNBLOCK_COMMENTS_USER = "UNBLOCK_COMMENT";

export const SET_REPLY_COMMENT = "SET_REPLY_COMMENT";

export const CLEAR_REPLY_COMMENT = "CLEAR_REPLY_COMMENT";

export const CLEAR_CREATE_COMMENT_SUCCESS = "CLEAR_CREATE_COMMENT_SUCCESS";

export const CHANGE_POST_SUBCATEGORIES = "CHANGE_POST_SUBCATEGORIES";

export const CHANGE_POSTS_VIEW = "CHANGE_POSTS_VIEW";

export const HIDE_FROM_FEED = "HIDE_FROM_FEED";

export const SET_EVENT_POST_SETTINGS_INITIAL_FORM_DATA =
  "SET_EVENT_POST_SETTINGS_INITIAL_FORM_DATA";

export const SET_RESUME_DETAIL_INFO_CACHE = "SET_RESUME_DETAIL_INFO_CACHE";

export const SET_SELECTED_RESUME_SUBCATEGORIES =
  "SET_SELECTED_RESUME_SUBCATEGORIES";

export const SET_POST_DETAIL = "SET_POST_DETAIL";

export const SET_POST_COMMENTS_THEME = "SET_POST_COMMENTS_THEME";

export const CLEAR_POST_COMMENTS = "CLEAR_POST_COMMENTS";

export const REPLACE_ORGANIZATION_POSTS = "REPLACE_ORGANIZATION_POSTS";
