export const SET_ORG_TRANSACTIONS = 'SET_ORG_TRANSACTIONS';
export const SET_RECEIPT_SALE_DETAIL = 'SET_RECEIPT_SALE_DETAIL';
export const SET_RECEIPT_DETAIL = 'SET_RECEIPT_DETAIL';
export const SET_RECEIPTS = 'SET_RECEIPTS';
export const SET_PREPROCESSTRANSACTION = 'SET_PREPROCESSTRANSACTION';

export const GET_TRANSACTIONS = {
  REQUEST: 'GET_TRANSACTIONS_REQUEST',
  SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
  FAILURE: 'GET_TRANSACTIONS_FAILURE',
}

export const GET_TRANSACTIONS_USERS = {
  REQUEST: 'GET_TRANSACTIONS_USERS_REQUEST',
  SUCCESS: 'GET_TRANSACTIONS_USERS_SUCCESS',
  FAILURE: 'GET_TRANSACTIONS_USERS_FAILURE',
}

export const GET_ORG_TRANSACTIONS_RECEIPTS = {
  REQUEST: 'GET_ORG_TRANSACTIONS_RECEIPTS_REQUEST',
  SUCCESS: 'GET_ORG_TRANSACTIONS_RECEIPTS_SUCCESS',
  FAILURE: 'GET_ORG_TRANSACTIONS_RECEIPTS_FAILURE'
}

// Rent transactions
export const SET_RENT_RECEIPT_DETAIL = 'SET_RENT_RECEIPT_DETAIL';

export const GET_RENT_TRANSACTION_DETAIL = {
  REQUEST: 'GET_RENT_TRANSACTION_DETAIL_REQUEST',
  SUCCESS: 'GET_RENT_TRANSACTION_DETAIL_SUCCESS',
  FAILURE: 'GET_RENT_TRANSACTION_DETAIL_FAILURE'
}