export const SET_TOTAL_CART_AMOUNT = 'SET_TOTAL_CART_AMOUNT';
export const SET_UNPROCESSED_TRANS_COUNT = 'SET_UNPROCESSED_TRANS_COUNT';

export const SET_RENT_UNPROCESSED_TRANS_COUNT = 'SET_RENT_UNPROCESSED_TRANS_COUNT';

export const SET_EVENT_UNPROCESSED_TRANS_COUNT = 'SET_EVENT_UNPROCESSED_TRANS_COUNT';