export const GET_STATISTIC_SUMMARY = 'GET_STATISTIC_SUMMARY';
export const GET_ORG_PARTNERS_STATISTIC_SUMMARY = 'GET_ORG_PARTNERS_STATISTIC_SUMMARY';

// ---- here ---- //
export const SET_USER_STATISTIC_SALE_TOTALS = 'SET_USER_STATISTIC_SALE_TOTALS';
export const SET_USER_STATISTIC_TOTALS = 'SET_USER_STATISTIC_TOTALS';
export const SET_ORG_GENERAL_STATISTICS = 'SET_ORG_GENERAL_STATISTICS';

// rent
export const SET_USER_STATISTIC_RENT_SALE_TOTALS = 'SET_USER_STATISTIC_RENT_SALE_TOTALS';
export const SET_USER_STATISTIC_RENT_TOTALS = 'SET_USER_STATISTIC_RENT_TOTALS';
export const SET_ORGANIZATION_RENT_SALE_TOTALS = 'SET_ORGANIZATION_RENT_SALE_TOTALS'
export const SET_RENT_DETAIL_SALE_TOTALS = 'SET_RENT_DETAIL_SALE_TOTALS';

// event
export const SET_USER_STATISTIC_EVENT_SALE_TOTALS = 'SET_USER_STATISTIC_EVENT_SALE_TOTALS';
export const SET_USER_EVENT_PURCHASE_TOTALS = 'SET_USER_EVENT_PURCHASE_TOTALS';
